name: ci
on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - '4.0'
  pull_request:
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ecs:
    name: ECS
    uses: craftcms/.github/.github/workflows/ecs.yml@v1
  phpstan:
    name: PHPStan
    uses: craftcms/.github/.github/workflows/phpstan.yml@v1
  codecept:
    name: Codeception
    uses: craftcms/.github/.github/workflows/codecept.yml@v1
    with:
      php_versions: '["8.0", "8.1"]'
  notify-slack:
    if: ${{ always() }}
    name: Notify Slack
    needs: [ ecs, phpstan, codecept ]
    uses: craftcms/.github/.github/workflows/notify-slack.yml@v1
    with:
      success: ${{ needs.ecs.result == 'success' && needs.phpstan.result == 'success' && needs.codecept.result == 'success' }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
      slack_group_id: ${{ secrets.SLACK_GROUP_ID }}