name: ci
on:
  workflow_dispatch:
  push:
    branches:
      - develop
  pull_request:
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ecs:
    name: ECS
    uses: craftcms/.github/.github/workflows/ecs.yml@v1
  codecept:
    name: Codeception
    uses: craftcms/.github/.github/workflows/codecept.yml@v1
    with:
      php_versions: '["7.2", "7.3", "7.4", "8.0", "8.1"]'
  notify-slack:
    name: Notify Slack
    needs: [ ecs, codecept ]
    if: ${{ always() }}
    uses: craftcms/.github/.github/workflows/notify-slack.yml@v1
    with:
      success: ${{ needs.ecs.result == 'success' && needs.codecept.result == 'success' }}
      failure_text_prefix: <!subteam^S01CWPYH9D5>
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      slack_webhook_url: ${{ secrets.SLACK_COMMERCE_WEBHOOK_URL }}
